### ISSUE TITLE
项目信息

### ISSUE THREAD

**Issue by fuyadong** [pythonsite/lyanna#1]
项目运行起来了，
go build main.go
go run main

数据库也配置了，打开页面没有数据，怎么添加数据？

项目与github是如何关联的？ 若给予答复非常感谢～

web 界面用什么开发的呢，是js?

**Comment by pythonsite** [comment]
项目里包含了前端的代码，你自己需要去数据库的添加一个管理员账户，管理员后台是/admin/login

**Comment by pythonsite** [comment]
因为现在项目还是一个初版，所以关于部署说明我并没有写的比较完善，我后面会完善一下，如果有问题着急也可以加入qq群948510543，我看到都会及时回复
